// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: progress.proto

package progress

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgressService_TrackProgress_FullMethodName       = "/progress.ProgressService/TrackProgress"
	ProgressService_GetLessonProgress_FullMethodName   = "/progress.ProgressService/GetLessonProgress"
	ProgressService_GetCourseProgress_FullMethodName   = "/progress.ProgressService/GetCourseProgress"
	ProgressService_GetUserProgress_FullMethodName     = "/progress.ProgressService/GetUserProgress"
	ProgressService_MarkLessonComplete_FullMethodName  = "/progress.ProgressService/MarkLessonComplete"
	ProgressService_ResetCourseProgress_FullMethodName = "/progress.ProgressService/ResetCourseProgress"
)

// ProgressServiceClient is the client API for ProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgressServiceClient interface {
	TrackProgress(ctx context.Context, in *TrackProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	GetLessonProgress(ctx context.Context, in *GetLessonProgressRequest, opts ...grpc.CallOption) (*LessonProgressResponse, error)
	GetCourseProgress(ctx context.Context, in *GetCourseProgressRequest, opts ...grpc.CallOption) (*CourseProgressResponse, error)
	GetUserProgress(ctx context.Context, in *GetUserProgressRequest, opts ...grpc.CallOption) (*UserProgressResponse, error)
	MarkLessonComplete(ctx context.Context, in *MarkLessonCompleteRequest, opts ...grpc.CallOption) (*LessonProgressResponse, error)
	ResetCourseProgress(ctx context.Context, in *ResetCourseProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type progressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgressServiceClient(cc grpc.ClientConnInterface) ProgressServiceClient {
	return &progressServiceClient{cc}
}

func (c *progressServiceClient) TrackProgress(ctx context.Context, in *TrackProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, ProgressService_TrackProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetLessonProgress(ctx context.Context, in *GetLessonProgressRequest, opts ...grpc.CallOption) (*LessonProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonProgressResponse)
	err := c.cc.Invoke(ctx, ProgressService_GetLessonProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetCourseProgress(ctx context.Context, in *GetCourseProgressRequest, opts ...grpc.CallOption) (*CourseProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseProgressResponse)
	err := c.cc.Invoke(ctx, ProgressService_GetCourseProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetUserProgress(ctx context.Context, in *GetUserProgressRequest, opts ...grpc.CallOption) (*UserProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProgressResponse)
	err := c.cc.Invoke(ctx, ProgressService_GetUserProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) MarkLessonComplete(ctx context.Context, in *MarkLessonCompleteRequest, opts ...grpc.CallOption) (*LessonProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonProgressResponse)
	err := c.cc.Invoke(ctx, ProgressService_MarkLessonComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) ResetCourseProgress(ctx context.Context, in *ResetCourseProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProgressService_ResetCourseProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgressServiceServer is the server API for ProgressService service.
// All implementations must embed UnimplementedProgressServiceServer
// for forward compatibility.
type ProgressServiceServer interface {
	TrackProgress(context.Context, *TrackProgressRequest) (*ProgressResponse, error)
	GetLessonProgress(context.Context, *GetLessonProgressRequest) (*LessonProgressResponse, error)
	GetCourseProgress(context.Context, *GetCourseProgressRequest) (*CourseProgressResponse, error)
	GetUserProgress(context.Context, *GetUserProgressRequest) (*UserProgressResponse, error)
	MarkLessonComplete(context.Context, *MarkLessonCompleteRequest) (*LessonProgressResponse, error)
	ResetCourseProgress(context.Context, *ResetCourseProgressRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProgressServiceServer()
}

// UnimplementedProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgressServiceServer struct{}

func (UnimplementedProgressServiceServer) TrackProgress(context.Context, *TrackProgressRequest) (*ProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetLessonProgress(context.Context, *GetLessonProgressRequest) (*LessonProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLessonProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetCourseProgress(context.Context, *GetCourseProgressRequest) (*CourseProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetUserProgress(context.Context, *GetUserProgressRequest) (*UserProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProgress not implemented")
}
func (UnimplementedProgressServiceServer) MarkLessonComplete(context.Context, *MarkLessonCompleteRequest) (*LessonProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkLessonComplete not implemented")
}
func (UnimplementedProgressServiceServer) ResetCourseProgress(context.Context, *ResetCourseProgressRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetCourseProgress not implemented")
}
func (UnimplementedProgressServiceServer) mustEmbedUnimplementedProgressServiceServer() {}
func (UnimplementedProgressServiceServer) testEmbeddedByValue()                         {}

// UnsafeProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgressServiceServer will
// result in compilation errors.
type UnsafeProgressServiceServer interface {
	mustEmbedUnimplementedProgressServiceServer()
}

func RegisterProgressServiceServer(s grpc.ServiceRegistrar, srv ProgressServiceServer) {
	// If the following call pancis, it indicates UnimplementedProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgressService_ServiceDesc, srv)
}

func _ProgressService_TrackProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).TrackProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_TrackProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).TrackProgress(ctx, req.(*TrackProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetLessonProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetLessonProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetLessonProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetLessonProgress(ctx, req.(*GetLessonProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetCourseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetCourseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetCourseProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetCourseProgress(ctx, req.(*GetCourseProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetUserProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetUserProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetUserProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetUserProgress(ctx, req.(*GetUserProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_MarkLessonComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkLessonCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).MarkLessonComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_MarkLessonComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).MarkLessonComplete(ctx, req.(*MarkLessonCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_ResetCourseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCourseProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).ResetCourseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_ResetCourseProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).ResetCourseProgress(ctx, req.(*ResetCourseProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgressService_ServiceDesc is the grpc.ServiceDesc for ProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "progress.ProgressService",
	HandlerType: (*ProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackProgress",
			Handler:    _ProgressService_TrackProgress_Handler,
		},
		{
			MethodName: "GetLessonProgress",
			Handler:    _ProgressService_GetLessonProgress_Handler,
		},
		{
			MethodName: "GetCourseProgress",
			Handler:    _ProgressService_GetCourseProgress_Handler,
		},
		{
			MethodName: "GetUserProgress",
			Handler:    _ProgressService_GetUserProgress_Handler,
		},
		{
			MethodName: "MarkLessonComplete",
			Handler:    _ProgressService_MarkLessonComplete_Handler,
		},
		{
			MethodName: "ResetCourseProgress",
			Handler:    _ProgressService_ResetCourseProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "progress.proto",
}
