// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: enrollment.proto

package enrollment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_EnrollCourse_FullMethodName          = "/enrollment.EnrollmentService/EnrollCourse"
	EnrollmentService_GetEnrollment_FullMethodName         = "/enrollment.EnrollmentService/GetEnrollment"
	EnrollmentService_ListEnrollments_FullMethodName       = "/enrollment.EnrollmentService/ListEnrollments"
	EnrollmentService_GetStudentEnrollments_FullMethodName = "/enrollment.EnrollmentService/GetStudentEnrollments"
	EnrollmentService_GetCourseEnrollments_FullMethodName  = "/enrollment.EnrollmentService/GetCourseEnrollments"
	EnrollmentService_CancelEnrollment_FullMethodName      = "/enrollment.EnrollmentService/CancelEnrollment"
	EnrollmentService_CompleteEnrollment_FullMethodName    = "/enrollment.EnrollmentService/CompleteEnrollment"
	EnrollmentService_IsUserEnrolled_FullMethodName        = "/enrollment.EnrollmentService/IsUserEnrolled"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollmentServiceClient interface {
	EnrollCourse(ctx context.Context, in *EnrollCourseRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	GetStudentEnrollments(ctx context.Context, in *GetStudentEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	GetCourseEnrollments(ctx context.Context, in *GetCourseEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	CancelEnrollment(ctx context.Context, in *CancelEnrollmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompleteEnrollment(ctx context.Context, in *CompleteEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	IsUserEnrolled(ctx context.Context, in *IsUserEnrolledRequest, opts ...grpc.CallOption) (*IsUserEnrolledResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) EnrollCourse(ctx context.Context, in *EnrollCourseRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_EnrollCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_GetEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) GetStudentEnrollments(ctx context.Context, in *GetStudentEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_GetStudentEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) GetCourseEnrollments(ctx context.Context, in *GetCourseEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_GetCourseEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) CancelEnrollment(ctx context.Context, in *CancelEnrollmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EnrollmentService_CancelEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) CompleteEnrollment(ctx context.Context, in *CompleteEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_CompleteEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) IsUserEnrolled(ctx context.Context, in *IsUserEnrolledRequest, opts ...grpc.CallOption) (*IsUserEnrolledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsUserEnrolledResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_IsUserEnrolled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
type EnrollmentServiceServer interface {
	EnrollCourse(context.Context, *EnrollCourseRequest) (*EnrollmentResponse, error)
	GetEnrollment(context.Context, *GetEnrollmentRequest) (*EnrollmentResponse, error)
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	GetStudentEnrollments(context.Context, *GetStudentEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	GetCourseEnrollments(context.Context, *GetCourseEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	CancelEnrollment(context.Context, *CancelEnrollmentRequest) (*emptypb.Empty, error)
	CompleteEnrollment(context.Context, *CompleteEnrollmentRequest) (*EnrollmentResponse, error)
	IsUserEnrolled(context.Context, *IsUserEnrolledRequest) (*IsUserEnrolledResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) EnrollCourse(context.Context, *EnrollCourseRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollCourse not implemented")
}
func (UnimplementedEnrollmentServiceServer) GetEnrollment(context.Context, *GetEnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollment not implemented")
}
func (UnimplementedEnrollmentServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedEnrollmentServiceServer) GetStudentEnrollments(context.Context, *GetStudentEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentEnrollments not implemented")
}
func (UnimplementedEnrollmentServiceServer) GetCourseEnrollments(context.Context, *GetCourseEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseEnrollments not implemented")
}
func (UnimplementedEnrollmentServiceServer) CancelEnrollment(context.Context, *CancelEnrollmentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelEnrollment not implemented")
}
func (UnimplementedEnrollmentServiceServer) CompleteEnrollment(context.Context, *CompleteEnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteEnrollment not implemented")
}
func (UnimplementedEnrollmentServiceServer) IsUserEnrolled(context.Context, *IsUserEnrolledRequest) (*IsUserEnrolledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserEnrolled not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_EnrollCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).EnrollCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_EnrollCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).EnrollCourse(ctx, req.(*EnrollCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_GetEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).GetEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_GetEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).GetEnrollment(ctx, req.(*GetEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_GetStudentEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).GetStudentEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_GetStudentEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).GetStudentEnrollments(ctx, req.(*GetStudentEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_GetCourseEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).GetCourseEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_GetCourseEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).GetCourseEnrollments(ctx, req.(*GetCourseEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_CancelEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).CancelEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_CancelEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).CancelEnrollment(ctx, req.(*CancelEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_CompleteEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).CompleteEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_CompleteEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).CompleteEnrollment(ctx, req.(*CompleteEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_IsUserEnrolled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserEnrolledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).IsUserEnrolled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_IsUserEnrolled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).IsUserEnrolled(ctx, req.(*IsUserEnrolledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrollment.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollCourse",
			Handler:    _EnrollmentService_EnrollCourse_Handler,
		},
		{
			MethodName: "GetEnrollment",
			Handler:    _EnrollmentService_GetEnrollment_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _EnrollmentService_ListEnrollments_Handler,
		},
		{
			MethodName: "GetStudentEnrollments",
			Handler:    _EnrollmentService_GetStudentEnrollments_Handler,
		},
		{
			MethodName: "GetCourseEnrollments",
			Handler:    _EnrollmentService_GetCourseEnrollments_Handler,
		},
		{
			MethodName: "CancelEnrollment",
			Handler:    _EnrollmentService_CancelEnrollment_Handler,
		},
		{
			MethodName: "CompleteEnrollment",
			Handler:    _EnrollmentService_CompleteEnrollment_Handler,
		},
		{
			MethodName: "IsUserEnrolled",
			Handler:    _EnrollmentService_IsUserEnrolled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enrollment.proto",
}
